### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Titaniumtown** [MierenManz/wacko#2]
Was wondering how to actually use this, there wasn't any information in the readme. Could this information be added?

**Comment by MierenManz** [comment]
Hi, thanks for the interest.
Right now I don't have a lot of docs because I feel like I may redo a few things. For now you can check out the tests.

I'll add smalls examples in the future.
If you need help you can always message me on discord `Bubbles#3553`

**Comment by MierenManz** [comment]
In ther repo there are now a few more tests and 2 really basic examples. I hope that can help a bit. Gonna be working on the optimization parts in my vacation and then later do the documentation

**Comment by Titaniumtown** [comment]
Ah ok, interesting. Thanks.
